/*
 * Pro Lab Overhead Stirrer
 * Hardware: NodeMCU ESP8266 + DRV8825 + MOONS 17HD8001-02 (NEMA17)
 *
 * config.h  -  Pin map, wiring constants and motor math.
 *
 * STEP/DIR driving:
 *  - STEP is generated by a hardware timer ISR for jitter-free pulses.
 *  - DRV8825 in 1/8 microstepping (M0=1, M1=1, M2=0).
 *  - 1.8 deg/step full -> 200 steps/rev -> 1600 steps/rev at 1/8.
 *    1/8 was chosen over full-step: it is SMOOTHER and produces more
 *    usable average torque at low-to-mid RPM for a stirrer, and the
 *    NodeMCU timer easily covers the required pulse rates. Full step
 *    would be slightly more efficient per pulse but far rougher and
 *    noisier; for a lab stirrer smoothness/torque ripple matter most.
 */

#ifndef CONFIG_H
#define CONFIG_H

#include <Arduino.h>

/* ------------------------------------------------------------------ */
/*  Wi-Fi Access Point credentials (controller is ALWAYS the AP)      */
/* ------------------------------------------------------------------ */
#define AP_SSID      "labst"
#define AP_PASSWORD  "mc142536"
#define AP_IP        192, 168, 4, 1
#define AP_GATEWAY   192, 168, 4, 1
#define AP_SUBNET    255, 255, 255, 0
#define HOSTNAME     "labst"

/* ------------------------------------------------------------------ */
/*  Pin map  (NodeMCU / ESP-12E GPIO numbers)                         */
/* ------------------------------------------------------------------ */
/*  DRV8825 microstep pins M0/M1/M2 are TIED on the PCB for a FIXED    */
/*  1/8 stepping (M0=1, M1=1, M2=0) so they do not use firmware pins.  */
/*  nSLEEP is tied to 3.3V (always awake). Only STEP/DIR/ENABLE/nRESET  */
/*  are driven by the MCU.                                              */
// DRV8825 (firmware controlled)
#define PIN_STEP      14   // D5  -> DRV STEP
#define PIN_DIR       12   // D6  -> DRV DIR
#define PIN_ENABLE    15   // D8  -> DRV ENABLE (active LOW)
#define PIN_RESET     13   // D7  -> DRV nRESET (active LOW)

// Front panel
#define PIN_POT       A0   // ADC -> potentiometer wiper
#define PIN_START     5    // D1  -> START button (pulled up, low = press)
#define PIN_STOP      4    // D2  -> STOP button  (pulled up, low = press)
#define PIN_DIRBTN    16   // D0  -> DIRECTION toggle button (pulled up)
#define PIN_LED       2    // D4  -> on-board heartbeat / status LED

// Sensor / protection
// NTC thermal sensing requires extra hardware (CD4051 mux or dedicated
// divider) on the single ADC. It is DISABLED by default so the POT can own
// A0. Define NTC_ENABLED in build_flags to enable the readNTC() sampling.
#define NTC_ENABLED   0
#define PIN_NTC       A0   // NTC divider / mux output (only if NTC_ENABLED)
#define PIN_RELAY     0    // D3  -> power relay (HIGH = 12V rail ON)
                           // Used for "Automatic Driver Disable / power-cycle restart"
                           // NOTE: GPIO0 is boot-strap; keep external 10k pull-up to 3.3V.

/* ------------------------------------------------------------------ */
/*  Motor constants                                                   */
/* ------------------------------------------------------------------ */
#define MOTOR_STEPS_PER_REV   200   // 1.8 deg
#define MICROSTEPPING         8     // DRV8825 M0=1,M1=1,M2=0
#define STEPS_PER_REV         (MOTOR_STEPS_PER_REV * MICROSTEPPING)  // 1600

// DRV8825 Vref for MOONS 17HD8001-02 (1.2A/phase, sense R = 0.1 ohm)
//   I_trip = Vref / (5 * Rsense)  ->  Vref = I * 5 * Rsense = 1.2 * 5 * 0.1 = 0.6 V
// We set 1.0A to keep driver cool while retaining torque: 1.0*0.5 = 0.5V
#define DRV_VREF_TARGET_MV    500   // 0.50 V  -> ~1.0 A/phase (tune pot on module)

// RPM <-> step rate
//   steps/sec = RPM * STEPS_PER_REV / 60
#define RPM_TO_STEPS_PER_SEC(rpm)  ((rpm) * (long)STEPS_PER_REV / 60L)

#define RPM_MIN    1
#define RPM_MAX    1500

/* ------------------------------------------------------------------ */
/*  Timing / behaviour                                                */
/* ------------------------------------------------------------------ */
#define SOFT_ACCEL_TIME_MS   1500   // ramp time (soft start/stop)
#define HEARTBEAT_MS         500
#define POT_SAMPLE_MS        200
#define BUTTON_DEBOUNCE_MS   50
#define NTC_SAMPLE_MS        1000
#define ENABLE_TIMEOUT_MS    3000   // disable driver this long after run ends
#define WATCHDOG_MS          8000   // software watchdog; if loop stalls, restart
#define TEMP_LIMIT_C         70     // NTC board/ambient proxy limit -> fault
#define STALL_RESTARTS_MAX   5      // power-cycle recovery attempts before lockout

/* ------------------------------------------------------------------ */
/*  Persistent settings path (LittleFS, wear-level friendly)          */
/* ------------------------------------------------------------------ */
#define SETTINGS_FILE  "/settings.json"

#endif // CONFIG_H
